plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = mod_version
group = mod_group_id

repositories { mavenCentral() }

base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version
    runs {
        client { client(); systemProperty 'neoforge.enabledGameTestNamespaces', mod_id }
        server { server(); programArgument '--nogui'; systemProperty 'neoforge.enabledGameTestNamespaces', mod_id }
    }
    mods { "${mod_id}" { sourceSet(sourceSets.main) } }
}

dependencies { implementation "net.neoforged:neoforge:${neo_version}" }

tasks.withType(ProcessResources).configureEach {
    def props = [version: project.version, mod_id: mod_id, mod_name: mod_name]
    inputs.properties props
    filesMatching(['META-INF/neoforge.mods.toml']) { expand props }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
